#reference :  https://github.com/docker/build-push-action/issues/276

name: Docker Setup Buildx - other branchs

on:
  push:
    branches: [ debug ]
        
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./enac_base.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: enacrobotique/enac-base:${{ env.BRANCH }}
          build-args: |
             DEV="False"
             BRANCH=${{ env.BRANCH }}
